### ISSUE TITLE
add with overflow panic in ratatui-0.21.0/src/layout.rs:464:43

### ISSUE THREAD

**Issue by XizheYin-NJU** [tui-rs-revival/ratatui#243]
## Description

intersection panic at `ratatui-0.21.0/src/layout.rs:464:43`

## To Reproduce

version:
```
ratatui = "=0.21.0"
```

source code:
```rust
fn main() {
    let test_backend = ratatui::backend::TestBackend::new(58596, 58596);
    let _rect1 = if let Ok(x) = ratatui::backend::Backend::size(&(test_backend)) {
        x
    } else {
        use std::process;
        process::exit(0);
    };
    let _rect2 = ratatui::layout::Rect::new(58596, 58596, 58368, 0);
    let _local16 = ratatui::layout::Rect::intersection(_rect1, _rect2);
}
```

## Error message
```
thread 'main' panicked at 'attempt to add with overflow', /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ratatui-0.21.0/src/layout.rs:464:43
```

## Screenshots

![image](https://github.com/tui-rs-revival/ratatui/assets/62123683/a6b2ea59-1f31-4db2-a639-ea231ceb572e)

**Comment by sayanarijit** [comment]
Please stop creating redundant issues for such edge cases. A single issue should be enough for a cleanup. If you want to contribute, please create a single issue or a single cleanup PR where we can have proper discussions. Closing this.

**Comment by XizheYin-NJU** [comment]
Sorry for the trouble. I don't have a lot of experience with issues, and I thought there should be an issue for every mistake, but now I get it. I will sort these bugs out and put them into an issue. Thanks for correcting me!
