### ISSUE TITLE
add overflow bug at /ratatui-0.21.0/src/layout.rs:465:44

### ISSUE THREAD

**Issue by XizheYin-NJU** [tui-rs-revival/ratatui#244]
## Description

With my fuzzing tool I found a bug panic at ratatui-0.21.0/src/layout.rs:465:44

## To Reproduce

```
ratatui = "=0.21.0"
```

```rust
fn main() {
    let mut test_backend = ratatui::backend::TestBackend::new(8224, 8224);

    let _rect1 = if let Ok(x) = ratatui::backend::Backend::size(&(test_backend)) {
        x
    } else {
        use std::process;
        process::exit(0);
    };

    let _rect2 = ratatui::layout::Rect::new(8223, 65312, 8415, 8224);
    let _ = ratatui::layout::Rect::intersection(_rect1, _rect2);
}
```

## Error Message and Backtrace

```
thread 'main' panicked at 'attempt to add with overflow', /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ratatui-0.21.0/src/layout.rs:465:44
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
   3: ratatui::layout::Rect::intersection
             at /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ratatui-0.21.0/src/layout.rs:465:44
   4: ch13::main
             at ./src/main.rs:256:13
   5: core::ops::function::FnOnce::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
```

## Screenshots

![image](https://github.com/tui-rs-revival/ratatui/assets/62123683/ee5b0f3c-b202-41ab-a2bd-c021c909aad8)

**Comment by sayanarijit** [comment]
Please stop creating redundant issues for such edge cases. A single issue should be enough for a cleanup. If you want to contribute, please create a single issue or a single cleanup PR where we can have proper discussions. Closing this.
