### ISSUE TITLE
Sub overflow panic at ratatui-0.21.0/src/layout.rs:469:20

### ISSUE THREAD

**Issue by XizheYin-NJU** [tui-rs-revival/ratatui#248]
## Description

This testcase will panic at ratatui-0.21.0/src/layout.rs:469:20

## To Reproduce

```rust
fn main() {
    let _local4 = ratatui::layout::Rect::new(32528, 35, 0, 33);
    let mut _local5 = ratatui::backend::TestBackend::new(5, 2527);
    let _local12 = if let Ok(x) = ratatui::backend::Backend::size(&(_local5)) {
        x
    } else {
        use std::process;
        process::exit(0);
    };
    let _ = ratatui::layout::Rect::intersection(_local4, _local12);
}
```

## Error Message
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ratatui-0.21.0/src/layout.rs:469:20
```

## Screenshots

![image](https://github.com/tui-rs-revival/ratatui/assets/62123683/873d3cdd-f13a-406d-9169-ebe32eb68efb)

**Comment by sayanarijit** [comment]
Please stop creating redundant issues for such edge cases. A single issue should be enough for a cleanup. If you want to contribute, please create a single issue or a single cleanup PR where we can have proper discussions. Closing this.
