### ISSUE TITLE
The last panic in union at ratatui-0.21.0/src/layout.rs:451:43

### ISSUE THREAD

**Issue by XizheYin-NJU** [tui-rs-revival/ratatui#256]
## Description

This is the last bug found so far. Since this library is related to the graphical interface, I recommend performing thorough arithmetic overflow checks before conducting arithmetic operations such as addition and subtraction to ensure error-free program execution. Thank you very much for taking the time to review these bug reports! I hope this library can be widely adopted!

## To Reproduce

```rust
fn main() {
    let _local2 = ratatui::layout::Rect::new(13876, 13622, 14080, 128);
    let _local9 = ratatui::layout::Rect::new(65535, 11858, 4096, 0);
    let _local10 = ratatui::layout::Rect::union(_local2, _local9);
}
```

## Error Message
```
thread 'main' panicked at 'attempt to add with overflow', /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ratatui-0.21.0/src/layout.rs:451:43
```

## Screenshots

![image](https://github.com/tui-rs-revival/ratatui/assets/62123683/9bf7bcfb-dbfc-465d-b54f-206ff500a405)

**Comment by XizheYin-NJU** [comment]
> Please stop creating redundant issues for such edge cases. A single issue should be enough for a cleanup. If you want to contribute, please create a single issue or a single cleanup PR where we can have proper discussions. Closing this.

Sorry for the trouble. I don't have a lot of experience with issues, and I thought there should be an issue for every mistake, but now I get it. I will sort these bugs out and put them into an issue. If necessary, I want to contribute.
